#!/usr/bin/python
import os
import sys

file_name = 'bitly.tsv'
country_code = ""
cc_dict = {}
devices = {'Android','BlackBerry','Windows NT','iPhone','iPad','iPod','Linux','Macintosh','PLAYSTATION 3'}
def main(argv): 
    argv_dict = {}
    for item in argv:
       key,value = item.split("=")
       argv_dict[key] = value
    try:
        top = int(argv_dict['to1p'])
    except:
        top = 5

    try:
        message = argv_dict['message']
    except:
        message="Platforms by country code"

    with open(file_name, "r") as fh:
        next(fh)                                 # skip the first row which contains the header info
        for line in fh:
            country_code = line.split('\t')[6]      # split the row by tab to get the country code
            user_agent = line.split('\t')[1].split()
            try:
                 total_devices_country = {}
                 user_device = user_agent[1].replace("(","").replace(";","")
                 if (user_device == "compatible" and user_agent[4] == "Windows" and user_agent[5] == "NT"):
                    user_device = "Windows NT"
#
                 if (devices.intersection(set(user_agent))):
                    if (len(country_code) == 0):             # re-code blanks as None
                        country_code = "None"
#
                    if (country_code in cc_dict):                       # check if the country exists in dict
                        total_devices_country = cc_dict[country_code]   # get the country list totals
                        if (user_device in total_devices_country):      # check if the device exists in totals
                            total_devices_country[user_device] = total_devices_country[user_device] + 1
                        else:
                             total_devices_country[user_device] = 1      # initialize to 1
                    else:
                        total_devices_country[user_device] = 1
                    cc_dict[country_code] = total_devices_country       # add the total devices to the country
            except:
                 pass
#
        top_platforms = {}
        for country in cc_dict:
            top_platforms[country] = max(cc_dict[country].values())
        print "Top {top} {message}".format(top=top,message=message)
        for country in sorted(top_platforms.items(), key=lambda kv: kv[1],reverse=True)[0:top]:
            print "{country}:".format(country=country[0])
            for agent,count in sorted(cc_dict[country[0]].items(), key=lambda kv: kv[1],reverse=True)[0:5]:
                print "\t{agent}:\t\t{count}".format(agent=agent,count=count);

if __name__ == "__main__":
   main(sys.argv[1:])
