#!/usr/bin/python
import os
import sys 
class Config(object):
    config_dict = {}
    def __init__(self, filename="myfile.txt", overwrite_keys = True):
        self.filename = filename
        try:
            with open(filename) as f:
                 lines = f.readlines()
        except IOError:
            print "IOError occurred trying to read the filename = ",filename


        for line in lines:
            value = line.strip("\n").split("=",1)
            self.config_dict[value[0]] = value[1]

    def get(self,key):
        try:
            return self.config_dict[key]
        except:
            return
    def set(self,key,value):
        try:
            self.config_dict[key] = value
        except KeyError:
            print "Key Error occurred trying to add the key = " + key + " for the value = " + value
    def save(self):
        try:
            with open(self.filename, "w") as f:
                for i in self.config_dict.keys():
                    f.write(i + "=" + self.config_dict[i] + "\n")
        except IOError:
            print "IOError occurred trying to save the dictionary"

    def getAll(self):
        return self.config_dict

def main(argv):
    conf = Config ("myfile.txt")
    print conf.config_dict.keys()
    print conf.config_dict['db_password']
    print conf.get('db_passwo3rd')
    conf.set('test','message')

    print conf.getAll()
    conf.save()

if __name__ == "__main__":
   main(sys.argv[1:])

