#!/usr/bin/python
import os
import sys
def main(argv):
   required_args = set(['to','from'])
   valid_args = set(['to','from','subject','body'])

   print ('='*3)+"Arguements from user are {argv}".format(argv=argv)
   argv_dict = {}
   for item in argv:
      key,value = item.split("=")
      argv_dict[key] = value

   if (len(required_args.intersection(argv_dict)) == len(required_args)):
      print ('='*3)+"Required fields exist"
   else:
      print ('='*3)+"Not all Required fields are present"

   if (len(valid_args.intersection(argv_dict)) == len(valid_args)):
      print ('='*3)+"All fields are valid"
   else:
      print ('='*3)+"Not all fields are valid"

   header = '''From: argv_dict['from']
               To:  argv_dict['to']
               Subject: argv_dict['subject']
            '''
   msg = header + argv_dict['body']
   sendmail = os.popen(" -t","w")
   sendmail.write(msg)
   sendmail.close()

if __name__ == "__main__":
   main(sys.argv[1:])
