#!/usr/bin/python
import os
import sys
import time

def main(argv):
   argv_dict = {}
   for item in argv:
       key,value = item.split("=")
       argv_dict[key] = value
# Get the path to search
   try:
        path = argv_dict['dir']
   except:
        pass
# Get the sort direction
   sort_direction = False
   try:
        if (argv_dict['direction'] == "decending"):
            sort_direction = True
   except:
        pass

   print path
   file_dict = {}
   for filename in os.walk(path):
       print filename
       try:
           file_path =  filename[0]
           filenames = filename[2]
           if (len(filename[1]) == 0):       # sub-path
               for file_name in filenames:
                   full_path = file_path + "/" + file_name
                   file_size = os.path.getsize(full_path)
                   file_modified = time.ctime(os.path.getmtime(full_path))
                   file_dict[full_path] = [file_size,file_modified]
           else:
               for file_name in filenames:
                   full_path =  file_path + file_name
                   file_size = os.path.getsize(full_path)
                   file_modified = time.ctime(os.path.getmtime(full_path))
                   file_dict[full_path] = [file_size,file_modified]
       except:
           pass

   sList = sorted(file_dict.items(), key=lambda kv: kv[1],reverse=sort_direction)
   for key in sList:
       print key

if __name__ == "__main__":
   main(sys.argv[1:])
